"""update location table

Revision ID: 46964b69a522
Revises: 85b84f1c6103
Create Date: 2025-06-20 12:36:21.993454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46964b69a522'
down_revision: Union[str, None] = '85b84f1c6103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('district', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
