"""add auth table: emailverification and revoke_token

Revision ID: 8310ea8c8db7
Revises: 9ab7df85bf09
Create Date: 2025-06-27 23:28:42.856201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8310ea8c8db7'
down_revision: Union[str, None] = '9ab7df85bf09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
