"""update the revoked token lake

Revision ID: 9ab7df85bf09
Revises: f922223d9c8a
Create Date: 2025-06-24 10:56:37.705148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab7df85bf09'
down_revision: Union[str, None] = 'f922223d9c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_token', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('revoked_token', sa.Column('access_token', sa.Text(), nullable=False))
    op.add_column('revoked_token', sa.Column('refresh_token', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'revoked_token', ['refresh_token'])
    op.create_unique_constraint(None, 'revoked_token', ['access_token'])
    op.drop_column('revoked_token', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_token', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'revoked_token', type_='unique')
    op.drop_constraint(None, 'revoked_token', type_='unique')
    op.drop_column('revoked_token', 'refresh_token')
    op.drop_column('revoked_token', 'access_token')
    op.drop_column('revoked_token', 'id')
    # ### end Alembic commands ###
