"""update emailverification table

Revision ID: ea2d4de9ca34
Revises: 46964b69a522
Create Date: 2025-06-20 13:34:57.724600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2d4de9ca34'
down_revision: Union[str, None] = '46964b69a522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('email', sa.Text(), nullable=True))
    op.drop_constraint(op.f('email_verifications_user_id_key'), 'email_verifications', type_='unique')
    op.create_unique_constraint(None, 'email_verifications', ['email'])
    op.drop_constraint(op.f('email_verifications_user_id_fkey'), 'email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'email_verifications', 'users', ['email'], ['email'])
    op.drop_column('email_verifications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('email_verifications_user_id_fkey'), 'email_verifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'email_verifications', type_='unique')
    op.create_unique_constraint(op.f('email_verifications_user_id_key'), 'email_verifications', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('email_verifications', 'email')
    # ### end Alembic commands ###
